<a href="https://colab.research.google.com/github/veenadarsanan/OASIS/blob/main/segment_analysis_oasis_task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Load the zipped CSV file directly into a pandas DataFrame
df = pd.read_csv('/content/Twitter_Data.csv.zip')

# Display the first 5 rows of the DataFrame
display(df.head())

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [2]:
# Display general information about the DataFrame, including data types and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   clean_text  162976 non-null  object
 1   category    162973 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.5+ MB

In [3]:
# Check for missing values
print('Missing values before dropping:')
display(df.isnull().sum())

# Drop rows with any missing values as they are few and might cause issues in sentiment analysis.
df.dropna(inplace=True)

print('\nMissing values after dropping:')
display(df.isnull().sum())

Missing values before dropping:

clean_text    4
category      7
dtype: int64

Missing values after dropping:

clean_text    0
category      0
dtype: int64

In [4]:
# Convert 'category' column to integer type as it represents discrete sentiment labels
df['category'] = df['category'].astype(int)

# Display the distribution of sentiment categories
print('\nDistribution of Sentiment Categories:')
display(df['category'].value_counts())

Distribution of Sentiment Categories:

category
 1    72249
 0    55211
-1    35509
Name: count, dtype: int64